#!/usr/bin/env python3
"""Unsupported-file census for the mocap-cleaner corpus.

A file's `verification_state` is `unsupported` as soon as one finding has status `unsupported`
(report_output.elisa), so a single opaque call in an included driver module marks every file that
includes it. This census runs the checker over every mocap-cleaner source and law file and, for
each file, buckets the unsupported findings by kind and by the source file they come from. The
`origin` table answers "which few findings make most files unsupported" and therefore which gap to
close first. Sources are only read; the output is deterministic (no timings).

    scripts/mocap_census.py [--root ../mocap-cleaner] [--out docs/census] [--workers N]
"""
import argparse
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
import json
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
BINARY = Path(os.environ.get("ELISA_PROOF_BIN", ROOT / "build/elisa-proof")).resolve()


def run(path, timeout):
    try:
        result = subprocess.run([str(BINARY), "--json", str(path)], capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return None, "timeout"
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None, "invalid-json"
    return (data, None) if isinstance(data, dict) else (None, "invalid-report")


def finding_origin(finding, default):
    origin = finding.get("file") or default
    return Path(origin).name


def summarize(relative, data, error):
    entry = {"file": relative}
    if data is None:
        entry["state"] = error
        return entry
    summary = data.get("summary", {})
    entry["state"] = data.get("verification_state", "unknown")
    entry["proven"] = summary.get("proven", 0)
    entry["obligations"] = summary.get("obligations", 0)
    kinds = Counter()
    origins = Counter()
    for finding in data.get("findings", []):
        if finding.get("status") != "unsupported":
            continue
        kind = finding.get("kind", "?")
        kinds[kind] += 1
        line = finding.get("file_line", finding.get("line", 0))
        origins[f"{finding_origin(finding, relative)}:{line} {finding.get('function', finding.get('name', '?'))} {kind}"] += 1
    entry["unsupported_kinds"] = dict(sorted(kinds.items()))
    entry["unsupported_sites"] = sorted(origins)
    return entry


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT.parent / "mocap-cleaner")
    parser.add_argument("--out", type=Path, default=ROOT / "docs/census")
    parser.add_argument("--workers", type=int, default=max(1, min(os.cpu_count() or 4, 4)))
    parser.add_argument("--timeout-seconds", type=int, default=900)
    args = parser.parse_args()
    root = args.root.resolve()
    files = sorted([*root.glob("src/*/*.elisa"), *root.glob("proof/*.elisa")])
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        # Summarize in the worker: a full report can be hundreds of megabytes.
        entries = list(pool.map(lambda path: summarize(path.relative_to(root).as_posix(), *run(path, args.timeout_seconds)), files))

    states = Counter(entry["state"] for entry in entries)
    kind_files = Counter()
    site_files = defaultdict(list)
    for entry in entries:
        for kind in entry.get("unsupported_kinds", {}):
            kind_files[kind] += 1
        for site in entry.get("unsupported_sites", []):
            site_files[site].append(entry["file"])
    revision = subprocess.run(["git", "-C", str(root), "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "mocap-cleaner.json").write_text(json.dumps(
        {"schema": "elisa-proof-mocap-census-v1", "mocap_cleaner": revision, "files": entries}, indent=1) + "\n")
    lines = ["# mocap-cleaner unsupported-file census", "",
             f"mocap-cleaner `{revision}`, {len(entries)} files: "
             + ", ".join(f"{count} {state}" for state, count in sorted(states.items())) + ".",
             "A file is `unsupported` when any one finding has status `unsupported`; a finding in an",
             "included module therefore marks every includer. Generated by `scripts/mocap_census.py`.", "",
             "## Files", "", "| File | State | Proven | Obligations | Unsupported findings |", "| --- | --- | ---: | ---: | --- |"]
    for entry in entries:
        kinds = ", ".join(f"{kind} {count}" for kind, count in entry.get("unsupported_kinds", {}).items()) or "-"
        lines.append(f"| {entry['file']} | {entry['state']} | {entry.get('proven', '-')} | {entry.get('obligations', '-')} | {kinds} |")
    lines += ["", "## Unsupported kinds by file count", "", "| Kind | Files |", "| --- | ---: |"]
    lines += [f"| {kind} | {count} |" for kind, count in sorted(kind_files.items(), key=lambda item: (-item[1], item[0]))]
    lines += ["", "## Unsupported sites", "", "Each site (origin file:line, function, kind) and the files it marks unsupported.", "",
              "| Site | Files | Marked files |", "| --- | ---: | --- |"]
    for site, marked in sorted(site_files.items(), key=lambda item: (-len(item[1]), item[0])):
        lines.append(f"| {site} | {len(marked)} | {', '.join(Path(name).stem for name in marked)} |")
    (args.out / "mocap-cleaner.md").write_text("\n".join(lines) + "\n")
    print(f"mocap census: {len(entries)} files, " + ", ".join(f"{count} {state}" for state, count in sorted(states.items())))


if __name__ == "__main__":
    main()
